[package]
name = "spinoso-time"
version = "0.7.0"
authors = ["Ryan Lopopolo <rjl@hyperbo.la>"]
edition = "2021"
rust-version = "1.63.0"
description = """
Datetime handling for Artichoke Ruby
"""
repository = "https://github.com/artichoke/artichoke"
readme = "README.md"
license = "MIT"
keywords = ["artichoke", "date", "datetime", "spinoso", "time"]
categories = ["date-and-time"]

[features]
default = ["tzrs", "tzrs-local"]
tzrs = ["dep:once_cell", "dep:regex", "dep:strftime-ruby", "dep:tz-rs", "dep:tzdb"]
tzrs-local = ["tzrs", "tzdb?/local"]

[dependencies]
once_cell = { version = "1.12.0", optional = true }
regex =  { version = "1.5.5", default-features = false, features = ["std"], optional = true }
strftime-ruby = { version = "1.0.0", default-features = false, features = ["alloc"], optional = true }
tz-rs = { version = "0.6.12", default-features = false, features = ["std"], optional = true }
tzdb = { version = "0.4.0", default-features = false, optional = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
